// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kultr-screens/AppScreens.tsx": () => import("../components/mockups/kultr-screens/AppScreens.tsx"),
  "./components/mockups/kultr-screens/PromoBanner.tsx": () => import("../components/mockups/kultr-screens/PromoBanner.tsx")
};
